spring.application.name=nervous_system
# MongoDB Database Connection
spring.data.mongodb.uri=mongodb+srv://hotel_admin:4FlMVa54rc5Rpfx7@cluster0.jr063ea.mongodb.net/hotel_saas_db?appName=Cluster0

# Run the server on port 8080
server.port=8080